<a href="https://colab.research.google.com/github/faruk17035/3rd-Work/blob/main/3rd_work%2Bcalcium%2BAAC%2BSVM%2Bwithout_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
from google.colab import drive 
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [5]:
import pandas as pd
from pandas import read_excel
file_name = '/content/gdrive/MyDrive/calcium/cal_AAC.csv' 
#df = pd.read_excel(file_name, index_col=0)
df = pd.read_csv(file_name)
#print(df.head()) # print the first 5 rows
df

A1        A2        A3        A4        A5        A6        A7  \
0     0.034483  0.120690  0.043103  0.060345  0.051724  0.103448  0.017241   
1     0.062762  0.050209  0.041841  0.083682  0.037657  0.087866  0.012552   
2     0.084507  0.112676  0.028169  0.000000  0.000000  0.070423  0.014085   
3     0.085714  0.114286  0.028571  0.014286  0.000000  0.057143  0.014286   
4     0.085366  0.085366  0.073171  0.060976  0.109756  0.036585  0.000000   
...        ...       ...       ...       ...       ...       ...       ...   
1296  0.037500  0.000000  0.025000  0.012500  0.100000  0.087500  0.037500   
1297  0.036585  0.060976  0.012195  0.012195  0.097561  0.012195  0.048780   
1298  0.072289  0.036145  0.060241  0.048193  0.024096  0.060241  0.024096   
1299  0.141026  0.000000  0.038462  0.051282  0.025641  0.051282  0.000000   
1300  0.035294  0.023529  0.035294  0.047059  0.035294  0.047059  0.011765   

            A8        A9       A10  ...       A12       A13       A14  \
0     0.060345  0.094828  0.051724  ...  0.043103  0.025862  0.017241   
1     0.037657  0.062762  0.071130  ...  0.066946  0.025105  0.016736   
2     0.042254  0.098592  0.098592  ...  0.014085  0.014085  0.028169   
3     0.028571  0.100000  0.128571  ...  0.000000  0.014286  0.028571   
4     0.012195  0.073171  0.109756  ...  0.036585  0.036585  0.012195   
...        ...       ...       ...  ...       ...       ...       ...   
1296  0.050000  0.050000  0.187500  ...  0.050000  0.037500  0.050000   
1297  0.097561  0.036585  0.158537  ...  0.060976  0.048780  0.060976   
1298  0.024096  0.048193  0.096386  ...  0.048193  0.072289  0.096386   
1299  0.076923  0.025641  0.089744  ...  0.051282  0.038462  0.064103   
1300  0.094118  0.035294  0.094118  ...  0.105882  0.035294  0.082353   

           A15       A16       A17       A18       A19       A20  Target  
0     0.043103  0.060345  0.060345  0.068966  0.000000  0.017241       1  
1     0.066946  0.083682  0.054393  0.058577  0.008368  0.041841       1  
2     0.084507  0.098592  0.112676  0.042254  0.000000  0.014085       1  
3     0.085714  0.071429  0.114286  0.057143  0.000000  0.028571       1  
4     0.024390  0.060976  0.048780  0.036585  0.024390  0.012195       1  
...        ...       ...       ...       ...       ...       ...     ...  
1296  0.012500  0.050000  0.062500  0.087500  0.037500  0.012500       0  
1297  0.012195  0.036585  0.048780  0.048780  0.012195  0.085366       0  
1298  0.036145  0.072289  0.096386  0.012048  0.000000  0.036145       0  
1299  0.076923  0.115385  0.012821  0.064103  0.012821  0.012821       0  
1300  0.082353  0.058824  0.058824  0.011765  0.023529  0.070588       0  

[1301 rows x 21 columns]

In [6]:
from datetime import datetime
df.shape

(1301, 21)

In [7]:
#Split data into independent (X) and dependent(Y) columns

y = df['Target'].values
X = df.drop('Target', axis=1).values

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 100)


In [9]:
### Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [10]:
from sklearn.svm import SVC
start=datetime.now()
#clf = lgb.train(lgbm_params, d_train, 50) #50 iterations. Increase iterations for small learning rates
classifier = SVC(kernel = 'rbf', random_state = 0, probability=True)
classifier.fit(X_train, y_train)
stop=datetime.now()
execution_time_svm= stop-start
print("SVM  execution time is: ", execution_time_svm)

SVM  execution time is:  0:00:00.207715


In [11]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[209   0]
 [ 10  42]]


0.9616858237547893

## AUC calculate



In [13]:
p = classifier.predict_proba(X_test)[:,1]

In [14]:
from sklearn.metrics import roc_auc_score
print("AUC = ",roc_auc_score(y_test,p))

AUC =  0.9953993375046006


In [15]:
from sklearn.metrics import matthews_corrcoef,confusion_matrix

In [16]:
matthews_corrcoef(y_test,y_pred)

0.877958643900965

In [17]:
TP = cm[0][0]
TN = cm[1][1]
FP = cm[0][1]
FN = cm[1][0]
print('True Positives:', TP)
print('True Negatives:', TN)
print('False Positives:', FP)
print('False Negatives:', FN)

True Positives: 209
True Negatives: 42
False Positives: 0
False Negatives: 10


In [18]:
sensitivity=(TP/(TP+FN))
sensitivity

0.954337899543379

In [19]:
specificity = (TN/(TN+FP))
specificity

1.0

In [20]:
precision = (TP/(TP+FP))
recall = (TP/(TP+FN))
f1 = (2*(precision*recall))/(precision+recall)
f1

0.9766355140186915

## Now tuning SVM

In [21]:
start=datetime.now()
clf = SVC(kernel='rbf', C=10, gamma=0.001,probability=True) 
clf.fit(X_train,y_train) 
stop=datetime.now()
execution_time_svm= stop-start
print("SVM  execution time is: ", execution_time_svm)

SVM  execution time is:  0:00:00.203620


In [22]:
y_pred = clf.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]

In [23]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[207   2]
 [  8  44]]


0.9616858237547893

In [24]:
from sklearn.metrics import classification_report, confusion_matrix 
y_pred = clf.predict(X_test)

In [25]:
# print classification report 
print(classification_report(y_test, y_pred)) 

              precision    recall  f1-score   support

           0       0.96      0.99      0.98       209
           1       0.96      0.85      0.90        52

    accuracy                           0.96       261
   macro avg       0.96      0.92      0.94       261
weighted avg       0.96      0.96      0.96       261



In [26]:
p = clf.predict_proba(X_test)[:,1]

In [27]:
from sklearn.metrics import roc_auc_score
print("AUC = ",roc_auc_score(y_test,p))

AUC =  0.9800331247699668


In [28]:
from sklearn.metrics import matthews_corrcoef,confusion_matrix

In [29]:
matthews_corrcoef(y_test,y_pred)

0.8769734921993947

In [30]:
TP = cm[0][0]
TN = cm[1][1]
FP = cm[0][1]
FN = cm[1][0]
print('True Positives:', TP)
print('True Negatives:', TN)
print('False Positives:', FP)
print('False Negatives:', FN)

True Positives: 207
True Negatives: 44
False Positives: 2
False Negatives: 8


In [31]:
sensitivity=(TP/(TP+FN))
sensitivity

0.9627906976744186

In [32]:
specificity = (TN/(TN+FP))
specificity

0.9565217391304348

In [33]:
precision = (TP/(TP+FP))
recall = (TP/(TP+FN))
f1 = (2*(precision*recall))/(precision+recall)
f1

0.9764150943396227